AMQ role changes
redhat-cop/jboss_amq pull request #10
Opened 2018-09-27 16:04 UTC by jlozadad

This is a huge change because as i went through this role, it was harder to understand and follow what was going on. Although I'm not an expert on AMQ, they layout was kind of harder to go through. So I broke down some files and separated some areas so its easier to find or understand. List of changes:

* added gitlab-ci.yml in case if it is used on gitlab
* updated README to correct version of playbook and updated to 7.2
* made some spaces and change the area where the vars are located in defaults/
* Added molecule
*  Changed include to include_tasks
* each download option its separated into its own .yml file.
* added idempotency to some of the shells/command tasks.

2018-10-30 03:56 UTC, sabre1041 requested changes

2018-10-30 03:56 UTC, sabre1041 commented on tasks/rhn_url.yml
> + - block:
The formatting of the block statement is misaligned.

2018-10-30 03:56 UTC, sabre1041 commented on tasks/install.yml
> +    src: "{{ jboss_amq_artifact_name }}"
This does not point to the location the file is downloaded

2018-11-09 07:58 UTC, sabre1041 approved these changes

2018-11-09 07:58 UTC, merged

2019-02-07 09:31 UTC, AbrahamArellano commented
Hi, I'm checking your repo for a customer and there is a problem with this approach:
https://github.com/redhat-cop/jboss_amq/blob/master/tasks/configure/users-roles.yml

The problem is that the last security-setting for the match="#" is considered. The previous one is discarded. That means your script generated the following configuration and the admins does not have rights anymore.

    <security-settings>
      <security-setting match="#">
        <permission type="createNonDurableQueue" roles="admins"/>
        <permission type="deleteNonDurableQueue" roles="admins"/>
        <permission type="createDurableQueue" roles="admins"/>
        <permission type="deleteDurableQueue" roles="admins"/>
        <permission type="createAddress" roles="admins"/>
        <permission type="deleteAddress" roles="admins"/>
        <permission type="consume" roles="admins"/>
        <permission type="browse" roles="admins"/>
        <permission type="send" roles="admins"/>
        <!-- we need this otherwise ./artemis data imp wouldn't work -->
        <permission type="manage" roles="admins"/>
      </security-setting>
      **<security-setting match="#">
        <permission type="browse" roles="view"/>
      </security-setting>**
    </security-settings>

I'm working on a fix but my project is a little bit different from yours but I will try to contribute.